# Generated by Django 5.2.1 on 2025-05-23 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_student_learner_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='learner_reference_number',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Learner reference number must be exactly 12 digits and contain numbers only')]),
        ),
    ]
