name: Deploy Django to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run collectstatic
      run: |
        python manage.py collectstatic --noinput

    - name: Deploy to Render
      run: |
        curl -X POST "https://api.render.com/v1/services/<your-service-id>/deploys" \
          -H "Authorization: Bearer <your-api-token>"
